---
name: Check patch

on:
  push:
    branches:
      [master]
  pull_request:
    branches:
      [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-9
            container-name: el9stream
          - name: centos-stream-10
            container-name: el10stream

    name: Build on ${{ matrix.name }}

    env:
      ARTIFACTS_DIR: exported-artifacts

    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}
    
    steps:
      - name: Mark repository as safe
        run: git config --global --add safe.directory "$(pwd)"

      - name: Prepare environment
        run: |
          dnf install -y --setopt=tsflags=nodocs autoconf automake gettext-devel git systemd make git rpm-build dnf-plugins-core python3-devel
          dnf install -y --setopt=tsflags=nodocs python3-pycodestyle python3-pyflakes
      
      - uses: ovirt/checkout-action@main
        with:
          fetch-depth: 0
      
      - name: Autoreconf
        run: autoreconf -ivf

      - name: Configure
        run: ./configure

      - name: Run distcheck
        run: make -j distcheck
      
      - name: Build RPM
        run: |
          dnf builddep ovirt-log-collector.spec
          rpmbuild -D "_topdir ${PWD}/tmp.repos" -D "release_suffix .$(date -u +%Y%m%d%H%M%S).git$(git rev-parse --short HEAD)" -ta ./ovirt-log-collector-*.tar.gz
        
      - name: Collect artifacts
        run: |
          mkdir -p exported-artifacts
          find tmp.repos -iname \*rpm -exec mv "{}" exported-artifacts/ \;
          mv ./*tar.gz exported-artifacts/ 
      
      - name: Upload artifacts
        uses: ovirt/upload-rpms-action@main
        with:
          directory: ${{ env.ARTIFACTS_DIR }}
